name: cofee_lover
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  get: ^4.6.6
  hooks_riverpod: ^2.5.1
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  phosphor_flutter: ^2.0.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.3
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
